### ISSUE TITLE
FB and TW links in footer are blocked by ad blockers

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/website#82] opened 2018-05-22 18:58 UTC
The problem here is that if you use the social-icons or font-awesome class names in a site, most ad-blockers will block them.

**Comment by yanokwa** [comment] 2018-05-31 23:35
We'll likely have to define an `odk-social-icons` style and use that instead of `social-icons`. FIrst, look to see if `social-icons` has any meaningful style. If it doesnt, then we can drop it. If it doesn't, then it might be good to re-define it in `main.scss`

Then, some approaches that might work
* Find some way to set the `$fa-css-prefix` for the `fa-{service}-square` icons so it's `odk-{service}-square `and they don't get blocked.
* Bundle the font-awesome icons into a font (https://icomoon.io is what I've used in the past) and include that in the site instead.

**Comment by yanokwa** [comment] 2018-06-02 14:54
I just re-checked this issue and I'm not able to reproduce. Is everyone seeing this footer when they have adblock turned on?

<img width="1056" alt="screen shot 2018-06-02 at 07 53 48" src="https://user-images.githubusercontent.com/32369/40877705-195bcf4a-663a-11e8-8fae-577c0ad83ca9.png">

**Comment by yanokwa** [comment] 2018-06-19 23:13
I can't reproduce this, so I'm closing.

**Comment by linl33** [comment] 2018-06-19 23:28
I can reproduce this.
The GitHub and RSS feed icons are not visible either. 

![screenshot from 2018-06-19 16-26-23](https://user-images.githubusercontent.com/8204095/41629293-8e1d4484-73dd-11e8-9227-e16ff77b0323.png)

**Comment by yanokwa** [comment] 2018-06-19 23:32
What browser and adblocker are you using?

**Comment by linl33** [comment] 2018-06-19 23:50
Chrome
uBlock Origin

The entire `.social-icons` class is removed.

**Comment by adammichaelwood** [comment] 2018-06-19 23:55
Blocked for me, too. 

AdBlockUs on Firefox Developer edition (I have native browser blocking and tracking code blocking turned on.)

**Closed** 2018-08-09 13:41 UTC
Labels: help wanted
